apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "saurav-shop.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb | quote }}
  DB_USERNAME: {{ .Values.secrets.dbUsername | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  COOKIE_SECRET: {{ .Values.secrets.cookieSecret | quote }}
  SUPERADMIN_USERNAME: {{ .Values.secrets.superadminUsername | quote }}
  SUPERADMIN_PASSWORD: {{ .Values.secrets.superadminPassword | quote }}
