apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "saurav-shop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
        - name: app-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/index.js"]
          ports:
            - containerPort: {{ .Values.server.port }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          readinessProbe:
            tcpSocket:
              port: {{ .Values.server.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.server.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
