# Saurav Shop Vendure Pipeline

name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        run: docker build -f docker/prod.Dockerfile -t saurav-shop:ci-test .
